name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create environment files
        run: |
          echo "export const environment = {
            production: false,
            openaiApiKey: '${{ secrets.OPENAI_API_KEY }}',
            openaiApiUrl: 'https://api.openai.com/v1/chat/completions'
          };" > src/environments/environment.ts
          
          echo "export const environment = {
            production: true,
            openaiApiKey: '${{ secrets.OPENAI_API_KEY }}',
            openaiApiUrl: 'https://api.openai.com/v1/chat/completions'
          };" > src/environments/environment.prod.ts

      - name: Build
        run: npm run build -- --base-href=/chat-app/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PAT }}
          folder: dist/hello-world
          branch: gh-pages
          clean: true
          single-commit: true 